// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbxwrQWg7qnXNLQRBU5fNFlERnBXblZ4',
    appId: '1:1042421926922:android:31613f6af283ccefede3f3',
    messagingSenderId: '1042421926922',
    projectId: 'library-management-syste-fe798',
    databaseURL: 'https://library-management-syste-fe798-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'library-management-syste-fe798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFcmM9GUFlQKBLbCIaCOkxrwveQpa2MKs',
    appId: '1:1042421926922:ios:47773bdb5c6ae3edede3f3',
    messagingSenderId: '1042421926922',
    projectId: 'library-management-syste-fe798',
    databaseURL: 'https://library-management-syste-fe798-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'library-management-syste-fe798.appspot.com',
    iosClientId: '1042421926922-sr5strpsj419bsi7n0e9jh3r6b6mta6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksApp',
  );
}
